# .hf_environment.yml
name: movie-bot
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - gradio>=3.50.0
    - tiktoken>=0.5.0
    - requests>=2.28.0
    - python-dotenv>=0.19.0